### PR TITLE
Properly parse struct definition by rejecting invalid public identifiers, Fixes: #787

### LINKED ISSUE #787: Reject invalid `pub` in a `struct` definition
### What is wrong?
Currently, an invalid `pub` appearance is not rejected, e.g.,
```rust
pub struct Bar {
    pub x: i32
pub}
```

### How can it be fixed

Tweaking the below code will resolve the issue.
https://github.com/ethereum/fe/blob/1190d93ef644d4e993497bf27ce5a48068c872ba/crates/parser/src/grammar/types.rs#L28-L55

### PR DESCRIPTION
**Pull request by Narasimha1997**
Fix #787 
Before, the struct definitions like:
```
pub struct Bar {
    pub x: i32
pub}
```
were not rejected by the parser. (as mentioned in #787 ). This pull request fixes this issue.
Also tests are written to validate this.

@Y-Nak

### CODE REVIEW

File: crates/parser/src/grammar/types.rs [hunk 1]
```diff
@@ -43,6 +44,12 @@ pub fn parse_struct_def(
                 functions.push(parse_fn_def(par, pub_qual)?);
             }
             TokenKind::BraceClose => {
+                if pub_qual.is_some() {
+                    let tok: Token = par.next()?;
+                    par.unexpected_token_error(&tok, "failed to parse struct definition", vec![]);
+                    return Err(ParseFailed);
+                }
```
Comment (Y-Nak) [inline crates/parser/src/grammar/types.rs:51]:
```suggestion
            TokenKind::BraceClose if pub_qual.is_none() => {

```

It seems the if block is the same as the block of the `_` arm, so I think it would be better to use the match guard or return a more detailed error message if the `TokenKind::BraceClose` has its own check for `pub_qual`.

**Review by Y-Nak — COMMENTED** [review]
Thanks for submitting PR! 
Basically, you're on the right track. I left a nit and will merge this PR after it is addressed.

**Comment by Y-Nak** [comment]
Also, could you add `fix #787` to the PR comments so that the issue is automatically closed when the PR is merged?

**Comment by Narasimha1997** [comment]
@Y-Nak , I have updated the changes you suggested

File: crates/parser/src/grammar/types.rs (hunk 1 above)
Comment (Narasimha1997) [reply crates/parser/src/grammar/types.rs]: Done! decided to go with the former one.

**Comment by Y-Nak** [comment]
Thanks!
