### PR TITLE
Pretty printing of Fe AST

### LINKED ISSUE #531: failed to analyze lowered AST (duplicate type name)
Compiling this file:

```
struct tuple_bool_address_:
 m:bool
contract o:
 e:(bool,address)
```

```
thread 'main' panicked at 'failed to analyze lowered AST: [Diagnostic { severity: Error, message: "duplicate type name", labels: [Label { style: Primary, span: Span { start: 0, end: 0 }, message: "`tuple_bool_address_` first defined here" }, Label { style: Secondary, span: Span { start: 0, end: 35 }, message: "`tuple_bool_address_` redefined here" }], notes: [] }]', crates/driver/src/lib.rs:62:51
stack backtrace:
   0:     0x5558642d6100 - std::backtrace_rs::backtrace::libunwind::trace::h63b7a90188ab5fb3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5558642d6100 - std::backtrace_rs::backtrace::trace_unsynchronized::h80aefbf9b851eca7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5558642d6100 - std::sys_common::backtrace::_print_fmt::hbef05ae4237a4d72
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5558642d6100 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h28abce2fdb9884c2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5558642eee4f - core::fmt::write::h3b84512577ca38a8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:     0x5558642d3a22 - std::io::Write::write_fmt::h465f8feea02e2aa1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:     0x5558642d8295 - std::sys_common::backtrace::_print::h525280ee0d29bdde
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5558642d8295 - std::sys_common::backtrace::print::h1f0f5b9f3ef8fb78
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5558642d8295 - std::panicking::default_hook::{{closure}}::ha5838f6faa4a5a8f
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:     0x5558642d7d43 - std::panicking::default_hook::hfb9fe98acb0dcb3b
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:     0x555864221b66 - fe_common::panic::DEFAULT_PANIC_HOOK::{{closure}}::{{closure}}::hfa0d7480b545d3da

You've hit an internal compiler error. This is a bug in the Fe compiler.
Fe is still under heavy development, and isn't yet ready for production use.

If you would, please report this bug at the following URL:
  https://github.com/ethereum/fe/issues/new
Aborted
```

Using

```
[profile.dev]
debug = true
panic = "abort"
```

for fuzzing.  Using https://github.com/agroce/afl-compiler-fuzzer

### PR DESCRIPTION
**Pull request by g-r-a-n-t**
### What was wrong?

We can't print the AST.

I wanted to fix #531 by adding a `$` to the front of lowered tuple struct names (e.g. `$tuple_bool_u256`), but wasn't able to do so without breaking the lowering tests. This is because the lowering tests compare the RON serialized AST of a lowered source file to that of an AST from a parsed file. So by adding a character to the lowered AST that is illegal to the parser, we are unable to validate that part of the lowering phase.

By making the AST printable, we can replace the existing lowering tests with insta snapshots and not have to be bound by grammar rules when lowering.

### To-Do

[//]: # (Stay ahead of things, add list items here!)
- [ ] OPTIONAL: Update [Spec](https://github.com/ethereum/fe/blob/master/docs/src/spec/index.md) if applicable
- [x] Add entry to the [release notes](https://github.com/ethereum/fe/blob/master/newsfragments/README.md) (may forgo for trivial changes)

- [x] Clean up commit history

### CODE REVIEW

**Comment by sbillig** [comment]
@g-r-a-n-t Does Display give us enough functionality to indent the tree so that it's pretty?

Also, if I had my druthers, the parser ast tests would compare asts with spans and the text content of the span, but other ast printing would ignore the spans. Eg from rowan https://crates.io/crates/rowan
```
Root@0..7
  BinaryExpr@0..7
    BinaryExpr@0..5
      BinaryExpr@0..3
        Literal@0..1
          Number@0..1 "1"
        Plus@1..2 "+"
        Literal@2..3
          Number@2..3 "2"
      Plus@3..4 "+"
      Literal@4..5
        Number@4..5 "3"
    Plus@5..6 "+"
    Literal@6..7
      Number@6..7 "4"
```
Not suggesting you have to implement this; just something to consider as you ponder the design.

**Comment by g-r-a-n-t** [comment]
> Does Display give us enough functionality to indent the tree so that it's pretty?

I'm using [indenter](https://docs.rs/indenter/0.3.3/indenter/) the same way it's [used](https://github.com/g-r-a-n-t/yultsur/blob/ae854702e90b2c70e5c19961167f2b6f2aff32d2/src/yul.rs#L193-L198) in Yultsur's AST Display impl, so indents shouldn't be a problem. It may be reasonable to not use Display for other design reasons, but I can't think of any, so I just started doing it this way.

File: crates/lowering/src/names.rs [hunk 1]
```diff
@@ -9,7 +9,7 @@ pub fn list_expr_generator_fn_name(list_expr_type: &Array) -> String {
 
 /// The name of a lowered tuple struct definition.
 pub fn tuple_struct_name(tuple: &Tuple) -> String {
-    tuple.lower_snake()
+    format!("${}", tuple.lower_snake())
```
Comment (g-r-a-n-t) [inline crates/lowering/src/names.rs:12]: do this in another PR

File: crates/parser/src/ast.rs [hunk 2]
```diff
@@ -386,6 +389,327 @@ impl Spanned for ContractStmt {
...
+impl fmt::Display for GenericArg {
+    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
+        match self {
+            GenericArg::TypeDesc(node) => write!(f, "{}", node.kind),
+            GenericArg::Int(node) => write!(f, "{}", node.kind),
+        }
+    }
+}
+
+impl fmt::Display for SimpleImportName {
```
Comment (g-r-a-n-t) [inline crates/parser/src/ast.rs:476]: I just left the imports out for now, since we may not be settled on their design.

File: crates/parser/src/ast.rs [hunk 3]
```diff
@@ -386,6 +389,327 @@ impl Spanned for ContractStmt {
...
+                }
+            }
+            FuncStmt::Emit { name, args } => {
+                write!(f, "emit {}({})", name.kind, node_comma_joined(&args.kind))
+            }
+            FuncStmt::Expr { value } => write!(f, "{}", value.kind),
+            FuncStmt::Pass => write!(f, "pass"),
+            FuncStmt::Break => write!(f, "break"),
+            FuncStmt::Continue => write!(f, "continue"),
+            FuncStmt::Revert { .. } => write!(f, "revert"),
```
Comment (g-r-a-n-t) [inline crates/parser/src/ast.rs:632]: finish this

File: crates/parser/src/ast.rs [hunk 4]
```diff
@@ -386,6 +389,327 @@ impl Spanned for ContractStmt {
...
+            }
+            Expr::UnaryOperation { op, operand } => {
+                let operand = maybe_fmt_inner_with_parens(self, &operand.kind);
+                if op.kind == UnaryOperator::Not {
+                    write!(f, "{} {}", op.kind, operand)
+                } else {
+                    write!(f, "{}{}", op.kind, operand)
+                }
+            },
+            Expr::CompOperation { left, op, right } => {
```
Comment (g-r-a-n-t) [inline crates/parser/src/ast.rs:676]: do these need parens?

File: crates/parser/src/ast.rs [hunk 5]
```diff
@@ -439,3 +763,85 @@ impl fmt::Display for CompOperator {
...
+
+fn maybe_fmt_inner_with_parens(outer: &Expr, inner: &Expr) -> String {
+    if inner_expr_needs_parens(outer, inner) {
+        format!("({})", inner)
+    } else {
+        format!("{}", inner)
+    }
+}
+
+fn inner_expr_needs_parens(outer: &Expr, inner: &Expr) -> bool {
```
Comment (g-r-a-n-t) [inline crates/parser/src/ast.rs:799]: comment

File: crates/parser/src/ast.rs [hunk 6]
```diff
@@ -439,3 +763,85 @@ impl fmt::Display for CompOperator {
...
+    expr_power(outer) > expr_power(inner)
+}
+
+fn expr_power(expr: &Expr) -> usize {
```
Comment (g-r-a-n-t) [inline crates/parser/src/ast.rs:803]: comment

File: crates/parser/src/ast.rs (hunk 4 above)
Comment (g-r-a-n-t) [reply crates/parser/src/ast.rs:682]: I dont think so

File: crates/parser/src/ast.rs [hunk 7]
```diff
@@ -439,3 +769,93 @@ impl fmt::Display for CompOperator {
...
+/// e.g.
+/// In the expression `2 * (3 + 4)`, the power of an `*` operation is greater than the power of
+/// an `+` operation. If we do not account for this by wrapping the `+` operation in parentheses,
+/// then the expression changes meaning.
+fn inner_expr_needs_parens(outer: &Expr, inner: &Expr) -> bool {
+    expr_power(outer) > expr_power(inner)
+}
+
+/// Similar to binding power, but in terms of a whole expressions, as opposed to a token.
+fn expr_power(expr: &Expr) -> usize {
```
Comment (g-r-a-n-t) [inline crates/parser/src/ast.rs:817]: Im not sure if there is better terminology to use here..

File: crates/parser/src/ast.rs [hunk 8]
```diff
@@ -386,6 +389,333 @@ impl Spanned for ContractStmt {
...
+                    write!(f, "<{}>", comma_joined(&generic_args.kind))?;
+                }
+                write!(f, "({})", node_comma_joined(&args.kind))
+            }
+            Expr::List { elts } => write!(f, "[{}]", node_comma_joined(elts)),
+            Expr::Tuple { elts } => write!(f, "({})", node_comma_joined(elts)),
+            Expr::Bool(bool) => write!(f, "{}", bool),
+            Expr::Name(name) => write!(f, "{}", name),
+            Expr::Num(num) => write!(f, "{}", num),
+            Expr::Str(str) => write!(f, "{}", str),
```
Comment (g-r-a-n-t) [inline crates/parser/src/ast.rs:703]: this might need quotes

File: crates/parser/src/ast.rs [hunk 9]
```diff
@@ -386,6 +389,333 @@ impl Spanned for ContractStmt {
     }
 }
 
+impl fmt::Display for Module {
+    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
+        for stmt in self.body.iter() {
```
Comment (g-r-a-n-t) [inline crates/parser/src/ast.rs:394]: use line join function

File: crates/parser/src/ast.rs [hunk 10]
```diff
@@ -386,6 +389,333 @@ impl Spanned for ContractStmt {
...
+        }
+
+        Ok(())
+    }
+}
+
+impl fmt::Display for Struct {
+    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
+        writeln!(f, "struct {}:", self.name.kind)?;
+        writeln!(indented(f), "{}", node_comma_joined(&self.fields))
```
Comment (g-r-a-n-t) [inline crates/parser/src/ast.rs:449]: should be line joined

File: crates/parser/src/ast.rs [hunk 11]
```diff
@@ -386,6 +389,333 @@ impl Spanned for ContractStmt {
...
+            ContractStmt::Event(node) => write!(f, "{}", node.kind),
+            ContractStmt::Function(node) => write!(f, "{}", node.kind),
+        }
+    }
+}
+
+impl fmt::Display for Event {
+    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
+        writeln!(f, "event {}:", self.name.kind)?;
+        for field in self.fields.iter() {
```
Comment (g-r-a-n-t) [inline crates/parser/src/ast.rs:524]: use line join function

**Review by g-r-a-n-t — COMMENTED** [review]
noticed a few more things while working on #546

File: crates/parser/src/ast.rs [hunk 12]
```diff
@@ -439,3 +769,93 @@ impl fmt::Display for CompOperator {
...
+/// An inner expression needs parentheses if the power of the outer expression is greater than
+/// that of the inner.
+///
+/// e.g.
+/// In the expression `2 * (3 + 4)`, the power of an `*` operation is greater than the power of
+/// an `+` operation. If we do not account for this by wrapping the `+` operation in parentheses,
+/// then the expression changes meaning.
+fn inner_expr_needs_parens(outer: &Expr, inner: &Expr) -> bool {
+    expr_power(outer) > expr_power(inner)
+}
```
Comment (sbillig) [inline crates/parser/src/ast.rs:814]: The paren insertion logic isn't right. Eg the parens of `2 * (3 / 4)` are dropped. For left-associative ops, using `>` for the lhs of a binop, and `>=` for the rhs would suffice, but `**` is right-associative, so `(2 ** 3) ** 4` needs to keep its parens but `2 ** (3 ** 4)` doesn't.

Maybe there's a more elegant way, but I think of it as left and right binding power, ie the amount of attraction power an op has on its left and right operands, as in `infix_binding_power`. A single `expr_power` fn isn't sufficient, as the power an outer expr exerts on its lhs and rhs might be different, and the power an inner expr   responds with may differ depending on whether it's on the left or right.

File: crates/parser/src/ast.rs (hunk 4 above)
Comment (sbillig) [reply crates/parser/src/ast.rs:682]: Yeah, eg `(1 == 2) == (3 == 4)`

File: crates/parser/src/ast.rs (hunk 12 above)
Comment (g-r-a-n-t) [reply crates/parser/src/ast.rs]: Ok, updated it to use left and right binding power. I think it's correct now.

File: crates/parser/src/ast.rs (hunk 4 above)
Comment (g-r-a-n-t) [reply crates/parser/src/ast.rs:675]: `(a == b) == (c == d)` is equivalent to  `1 == 2 == (3 == 4)`, right? this is at least what the test are telling me, as the first set of parens are dropped when printing

**Comment by g-r-a-n-t** [comment]
I'm merging this @sbillig.

I'm fairly confident the paren stuff is correct now. It's also only going to be used for testing, so it's not something that needs to be perfect.
