### PR TITLE
Validate that tuple attributes are prefixed with 'item'

### LINKED ISSUE #396: failed to analyze lowered AST: SemanticError  { kind: UndefinedValue, context: [Span { start: 178, end: 201 }, Span { start: 178, end: 209 }, Span { start: 178, end: 244 }, Span { start: 171, end: 244 }, Span { start: 44, end: 326 }] } at compiler/src/lib.rs:54:60
Compiling this file:

```
contract o:
    my_sto_tuple:(u256,i32)
    pub def e(my_num:u256,my_bool:bool,my_address:address)->(u256,bool,address):
        return(my_num,my_bool,my_address)
        assert self.my_sto_tuple.iteo0>u256(0)and self.my_sto_tuple.item1==i32(0)
        e:(u256,bool,address)=(self.my_sto_tuple.item0,true and false,address(6))
```

```
thread 'main' panicked at 'failed to analyze lowered AST: SemanticError { kind: UndefinedValue, context: [Span { start: 178, end: 201 }, Span { start: 178, end: 209 }, Span { start: 178, end: 244 }, Span { start: 171, end: 244 }, Span { start: 44, end: 326 }] }', compiler/src/lib.rs:54:60
stack backtrace:
   0:     0x5589152ddde0 - std::backtrace_rs::backtrace::libunwind::trace::h9d49145f95eb5894
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5589152ddde0 - std::backtrace_rs::backtrace::trace_unsynchronized::hab1d020365bb6864
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5589152ddde0 - std::sys_common::backtrace::_print_fmt::h7659588431e304bd
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5589152ddde0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h09f4a9e3befae3c7
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5589152f7b3c - core::fmt::write::hf3fdfde304b9a088
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/core/src/fmt/mod.rs:1092:17
   5:     0x5589152dad42 - std::io::Write::write_fmt::h1cb850689c7116f0
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/io/mod.rs:1568:15
   6:     0x5589152dffa5 - std::sys_common::backtrace::_print::hdbccd5aa093ba544
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5589152dffa5 - std::sys_common::backtrace::print::hc639c4f320222558
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5589152dffa5 - std::panicking::default_hook::{{closure}}::hdb012dd7a485bb5d
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/panicking.rs:208:50
   9:     0x5589152dfa53 - std::panicking::default_hook::h75facbce77b6ba91
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/panicking.rs:225:9
  10:     0x558914a09bcf - fe_compiler::errors::DEFAULT_PANIC_HOOK::{{closure}}::{{closure}}::hd71e839699e0bfd6

You've hit an internal compiler error. This is a bug in the Fe compiler.
Fe is still under heavy development, and isn't yet ready for production use.

If you would, please report this bug at the following URL:
  https://github.com/ethereum/fe/issues/new
Aborted
```

On latest github master, built with

```
[profile.dev]
debug = true
panic = "abort"
```

for fuzzing.  Using https://github.com/agroce/afl-compiler-fuzzer

### LINKED ISSUE #399: byte index is out of bounds at analyzer/src/traversal/expressions.rs:369:5
Compiling this file:

```
contract o
    my_sto_tuple:(u256,i32)
    pub def e->(u256,bool,address)
        m:u256=self.my_sto_tuple.m
        return
```

```
thread 'main' panicked at 'byte index 4 is out of bounds of `m`', analyzer/src/traversal/expressions.rs:369:5
stack backtrace:
   0:     0x560cd7a2a710 - std::backtrace_rs::backtrace::libunwind::trace::h9d49145f95eb5894
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x560cd7a2a710 - std::backtrace_rs::backtrace::trace_unsynchronized::hab1d020365bb6864
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x560cd7a2a710 - std::sys_common::backtrace::_print_fmt::h7659588431e304bd
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x560cd7a2a710 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h09f4a9e3befae3c7
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x560cd7a4446c - core::fmt::write::hf3fdfde304b9a088
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/core/src/fmt/mod.rs:1092:17
   5:     0x560cd7a27672 - std::io::Write::write_fmt::h1cb850689c7116f0
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/io/mod.rs:1568:15
   6:     0x560cd7a2c8d5 - std::sys_common::backtrace::_print::hdbccd5aa093ba544
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x560cd7a2c8d5 - std::sys_common::backtrace::print::hc639c4f320222558
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x560cd7a2c8d5 - std::panicking::default_hook::{{closure}}::hdb012dd7a485bb5d
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/panicking.rs:208:50
   9:     0x560cd7a2c383 - std::panicking::default_hook::h75facbce77b6ba91
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/panicking.rs:225:9
  10:     0x560cd715bb4f - fe_compiler::errors::DEFAULT_PANIC_HOOK::{{closure}}::{{closure}}::hd71e839699e0bfd6

You've hit an internal compiler error. This is a bug in the Fe compiler.
Fe is still under heavy development, and isn't yet ready for production use.

If you would, please report this bug at the following URL:
  https://github.com/ethereum/fe/issues/new
Aborted
```

On latest github master, built with

```
[profile.dev]
debug = true
panic = "abort"
```

for fuzzing.  Using https://github.com/agroce/afl-compiler-fuzzer

### PR DESCRIPTION
**Pull request by g-r-a-n-t**
### What was wrong?

closes #396 and closes #399

### How was it fixed?

We weren't verifying that tuple attributes started with "item", which resulted in undefined attributes such as `iteo0` making it to the post-lowering analysis stage.

### To-Do

[//]: # (Stay ahead of things, add list items here!)
- [ ] OPTIONAL: Update [Spec](https://github.com/ethereum/fe/blob/master/spec/index.md) if applicable
- [x] Add entry to the [release notes](https://github.com/ethereum/fe/blob/master/newsfragments/README.md) (may forgo for trivial changes)

- [x] Clean up commit history

### CODE REVIEW

File: compiler/tests/cases/lowering/mod.rs [hunk 1]
```diff
@@ -47,5 +47,7 @@ fn test_lowering(fixture: &str) {
     assert_strings_eq!(
         replace_spans(to_ron_string_pretty(&expected_lowered_ast).unwrap()),
         replace_spans(to_ron_string_pretty(&actual_lowered_ast).unwrap()),
-    )
+    );
+
+    fe_analyzer::analyze(&actual_lowered_ast).expect("analysis of the lowered module failed");
```
Comment (g-r-a-n-t) [inline compiler/tests/cases/lowering/mod.rs:52]: Not necessarily related, but thought this would be helpful.

**Review by sbillig — APPROVED** [review]
lgtm
