### PR TITLE
Safe user-defined identifier mapping. 

### LINKED ISSUE #102: Ensure compiler generated methods can not conflict with user defined methods
### What is wrong?

Whenever we the compiler generates helper functions, that is, functions that aren't defined by the user, we need to ensure that they can not conflict with functions defined by the user. E.g. if we generate a function such as `abi_encode_uint256_address` we risk that a user may also create a function named `abi_encode_uint256_address` which can lead to undefined runtime behavior. 

### How can it be fixed

A simple fix would be to ensure all generated, non-user defined functions are prefixed with a symbol that is legal in YUL but illegal in Fe. E.g. instead of generating `abi_encode_uint256_address` we could generate `$abi_encode_uint256_address` instead.

### PR DESCRIPTION
**Pull request by g-r-a-n-t**
### What was wrong?

closes #102 

Identifiers chosen by users could conflict with identifiers introduced by the compiler.

### How was it fixed?

User-defined variable names now have `$` added to the front and user defined function names now have `$$` added to the front.

### To-Do

[//]: # (Stay ahead of things, add list items here!)
- [ ] OPTIONAL: Update [Spec](https://github.com/ethereum/fe/blob/master/spec/index.md) if applicable
- [x] Clean up commit history

### CODE REVIEW

File: compiler/src/yul/mappers/declarations.rs [hunk 1]
```diff
@@ -126,6 +127,9 @@ mod tests {
             }),
         );
 
-        assert_eq!(map(&harness.context, &harness.src), "let foo := alloc(200)");
+        assert_eq!(
+            map(&harness.context, &harness.src),
+            "let $foo := alloc(200)"
```
Comment (cburgdorf) [inline compiler/src/yul/mappers/declarations.rs:132]: Am I right to assume that all the runtime functions such as `alloc` should also turn into `$$alloc` (or maybe some scheme that sets them apart from user defined functions) to ensure those aren't callable by user code?

**Review by cburgdorf — APPROVED** [review]
Looks good. Just left a comment regarding runtime functions but we could move that into a separate issue.

File: compiler/src/yul/mappers/declarations.rs (hunk 1 above)
Comment (g-r-a-n-t) [reply compiler/src/yul/mappers/declarations.rs:132]: Anytime someone writes a call expressions (e.g. `foo(42)`), the function identifier will include `$$` after being mapped (`$$foo(42)`), so it should be impossible for someone to write something that calls `alloc` or any other runtime function directly.

Comment (cburgdorf) [reply compiler/src/yul/mappers/declarations.rs:132]: Ah, sure! :see_no_evil:
