### PR TITLE
Fix "analysis failed but no diagnostics were emitted" panics

### LINKED ISSUE #530: Analyzer not properly giving user error in certain cases of unknown type usage
### What is wrong?

Hit an ICE.

```
contract Foo:

    fn baz(needs_param_to_reproduce_crash: u256):
        pass

    pub fn bar(val: DoesntExist):
        baz(val)
```

Doesn't matter if the function takes `self` or not.

```
contract Foo:

    fn baz(self, needs_param_to_reproduce_crash: u256):
        pass

    pub fn bar(self, val: DoesntExist):
        self.baz(val)
```

Output
```
thread 'main' panicked at 'analysis of `fn bar` failed, but no diagnostics were emitted', crates/analyzer/src/db/queries/functions.rs:169:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

You've hit an internal compiler error. This is a bug in the Fe compiler.
Fe is still under heavy development, and isn't yet ready for production use.

If you would, please report this bug at the following URL:
  https://github.com/ethereum/fe/issues/new
```

### How can it be fixed

Investigate

### LINKED ISSUE #532: analysis of `fn return_casted_static_string` failed, but no diagnostics were emitted at crates/analyzer/src/db/queries/functions.rs:169:13
Compiling this file:

```
contract ERC20:
    pub fn return_casted_static_string() -> String<100>:
        return String<H00>("foo")
```

```
thread 'main' panicked at 'analysis of `fn return_casted_static_string` failed, but no diagnostics were emitted', crates/analyzer/src/db/queries/functions.rs:169:13
stack backtrace:
   0:     0x5568b6943100 - std::backtrace_rs::backtrace::libunwind::trace::h63b7a90188ab5fb3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5568b6943100 - std::backtrace_rs::backtrace::trace_unsynchronized::h80aefbf9b851eca7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5568b6943100 - std::sys_common::backtrace::_print_fmt::hbef05ae4237a4d72
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5568b6943100 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h28abce2fdb9884c2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5568b695be4f - core::fmt::write::h3b84512577ca38a8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:     0x5568b6940a22 - std::io::Write::write_fmt::h465f8feea02e2aa1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:     0x5568b6945295 - std::sys_common::backtrace::_print::h525280ee0d29bdde
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5568b6945295 - std::sys_common::backtrace::print::h1f0f5b9f3ef8fb78
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5568b6945295 - std::panicking::default_hook::{{closure}}::ha5838f6faa4a5a8f
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:     0x5568b6944d43 - std::panicking::default_hook::hfb9fe98acb0dcb3b
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:     0x5568b688eb66 - fe_common::panic::DEFAULT_PANIC_HOOK::{{closure}}::{{closure}}::hfa0d7480b545d3da

You've hit an internal compiler error. This is a bug in the Fe compiler.
Fe is still under heavy development, and isn't yet ready for production use.

If you would, please report this bug at the following URL:
  https://github.com/ethereum/fe/issues/new
Aborted

```

Using

```
[profile.dev]
debug = true
panic = "abort"
```

for fuzzing.  Using https://github.com/agroce/afl-compiler-fuzzer

### PR DESCRIPTION
**Pull request by sbillig**
### What was wrong?

closes #532 -  Here we weren't emitting an error message if the `String` type constructor was ill-formed. Eg `String<x>("hi")` would be rejected without an error message.

closes #530 - Here we were panicking because the fn body diagnostic vec was empty, even though the analysis failed. We shouldn't panic in this case, because an undefined type diagnostic was produced elsewhere (during the analysis of the function signature).

These cases are just symptoms of a problem in the analyzer; we require that a friendly diagnostic be emitted before returning FatalError or TypeError, but can't effectively ensure that that's happening.

### How was it fixed?

FatalError and TypeError now can't be created unless you have a voucher proving that you've emitted a diagnostic. You can receive such a voucher by calling an `AnalyzerContext` error function. For example:

```
Err(TypeError::new(scope.error("something is wrong", span, "this")))
```

I noticed some other error stuff that needs to be improved, and added TODO comments. I'll fix those in a follow-up PR.

### To-Do

[//]: # (Stay ahead of things, add list items here!)
- [x] Add entry to the [release notes](https://github.com/ethereum/fe/blob/master/newsfragments/README.md) (may forgo for trivial changes)

### CODE REVIEW

File: crates/analyzer/src/context.rs [hunk 1]
```diff
@@ -38,23 +39,56 @@ pub trait AnalyzerContext {
...
         ))
     }
+
+    fn register_diag(&mut self, diag: Diagnostic) -> DiagnosticVoucher {
+        self.add_diagnostic(diag);
+        DiagnosticVoucher(PhantomData::default())
+    }
+}
+
+/// This should only by [`AnalyzerContext`]
```
Comment (sbillig) [inline crates/analyzer/src/context.rs:77]: Uh, not sure what happened here. I'll fix this comment in my next PR.

File: crates/analyzer/src/errors.rs [hunk 2]
```diff
@@ -1,43 +1,67 @@
...
+/// If, for example, a function parameter has an undefined type, we emit a [`Diagnostic`] message,
+/// give that parameter a "type" of `Err(TypeError)`, and carry on. If/when that parameter is
+/// used in the function body, we assume that a diagnostic message about the undefined type
+/// has already been emitted, and halt the analysis of the function body.
+///
+/// To ensure that that assumption is sound, a diagnostic *must* be emitted before creating
+/// a `TypeError`. So that the rust compiler can help us enforce this rule, a `TypeError`
+/// cannot be constructed without providing a [`DiagnosticVoucher`]. A voucher can be obtained
+/// by calling an error function on an [`AnalyzerContext`](crate::context::AnalyzerContext).
+/// Please don't try to work around this restriction.
```
Comment (cburgdorf) [inline crates/analyzer/src/errors.rs:23]: Nice pattern :)

File: crates/analyzer/src/traversal/expressions.rs [hunk 3]
```diff
@@ -850,7 +833,15 @@ fn expr_call_type_constructor(
                 Location::Value,
             ))
         }
-        _ => Err(FatalError::new()),
+        Type::Struct(_) => unreachable!(), // handled above
+
+        // TODO: These type should be handled explicitly, either here or in expr_name_call_type.
```
Comment (cburgdorf) [inline crates/analyzer/src/traversal/expressions.rs:838]: Mind opening an issue about this?

File: crates/analyzer/src/traversal/expressions.rs [hunk 4]
```diff
@@ -1318,6 +1300,7 @@ fn expr_name_call_type(
     name: &str,
     generic_args: Option<&Node<Vec<fe::GenericArg>>>,
 ) -> Result<CallType, FatalError> {
+    // TODO: we're ignoring error cases like `u256<x>(10)` here
```
Comment (cburgdorf) [inline crates/analyzer/src/traversal/expressions.rs:1303]: Would be good to have an issue open for this, too

**Review by cburgdorf — APPROVED** [review]
Great hardening of the error system.

File: crates/analyzer/src/traversal/expressions.rs (hunk 3 above)
Comment (sbillig) [reply crates/analyzer/src/traversal/expressions.rs:838]: I've addressed these TODOs in a separate branch; I'll open a PR today.
