### PR TITLE
 v2 parser: change assignment's lhs to expression

### LINKED ISSUE #875: v2 parser AugAssign stmt doesn't allow `x[0] += 1`
### What is wrong?

The new parser (v2 branch) only supports augmented-assignments where the LHS is an identifier. Eg `x += 1` is supported, but `x.y += 1` isn't.

### How can it be fixed

Good opportunity for someone to become familiar with the new parser, I guess.

### PR DESCRIPTION
**Pull request by saifalkatout**
resolves #875 

What was wrong?

The new parser (v2 branch) wrongly supposes the assignment destination is a pattern, but it should be an expression.

How was it fixed?

change Assign and augassign to expressions

### CODE REVIEW

**Comment by saifalkatout** [comment]
Hey @Y-Nak, I created a new clean pull request for the parser issue.
Just a few comments: 
1) Are the `lazyspan`s acceptable ? do I need to write a test for the `LazyAssignSpan` ?


2) The new `bp`s will replicate the following issue
`x += 1 + 1` well produce
```
BinExpr@52..62
  AugAssignExpr@52..58
    PathExpr@52..53
      Path@52..53
        PathSegment@52..53
          Ident@52..53 "x"
    WhiteSpace@53..54 " "
    AugAssignExpr@54..58
      Plus@54..55 "+"
      Eq@55..56 "="
      WhiteSpace@56..57 " "
      LitExpr@57..58
        Lit@57..58
          Int@57..58 "1"
  WhiteSpace@58..59 " "
  Plus@59..60 "+"
  WhiteSpace@60..61 " "
  LitExpr@61..62
    Lit@61..62
      Int@61..62 "1"
``` 

3) commits will be squashed on finish

**Comment by Y-Nak** [comment]
First and foremost, please learn the basic usage of git. And please use git in the proper way since the next PR.  There is a vast amount of learning resources available online. This is the third PR on the same issue. I think it is generally not preferable to have reviews dispersed across multiple PRs, and it also increases my workload (albeit slightly). While I believe that the flow where reviewers and authors work together to resolve issues in the code is excellent, but frankly speaking, I don't want to teach basic git usage.

> Are the lazyspans acceptable ? do I need to write a test for the LazyAssignSpan ?

We need to get `=` span in `AssignExpr`, and don't need to get `expr` because all spans of `expr` is directly stored in `Body`. Also, we need to get binary operator span in `AugAssignExpr`.

> The new bps will replicate the following issue `x += 1 + 1` well produce

This problem has nothing to do with the binding power. You just need to modify `Plus | Minus` arm as you did in `Star | Slash | Percent` arm.

File: crates/parser2/src/ast/expr.rs [hunk 1]
```diff
@@ -927,4 +972,41 @@ mod tests {
         }
         assert_eq!(count, 3)
     }
+    #[test]
+    #[wasm_bindgen_test]
```
Comment (Y-Nak) [inline crates/parser2/src/ast/expr.rs:976]:
```suggestion
```

I'm not sure if we need a wasm test here, is there any specific reason to run wasm test for these tests?

File: crates/parser2/src/ast/expr.rs [hunk 2]
```diff
@@ -927,4 +972,41 @@ mod tests {
...
+            ExprKind::RecordInit(_)
+        ));
+        assert!(matches!(
+            assign_expr.rhs_expr().unwrap().kind(),
+            ExprKind::Path(_)
+        ));
+    }
+
+    #[test]
+    #[wasm_bindgen_test]
```
Comment (Y-Nak) [inline crates/parser2/src/ast/expr.rs:990]: ditto.

File: crates/parser2/src/parser/expr.rs [hunk 3]
```diff
@@ -164,9 +169,19 @@ fn infix_binding_power<S: TokenStream>(parser: &mut Parser<S>) -> Option<(u8, u8
         Amp => (100, 101),
         LShift | RShift => (110, 111),
         Plus | Minus => (120, 121),
```
Comment (Y-Nak) [inline crates/parser2/src/parser/expr.rs:171]: Please add `is_aug` branch for aug assign. Also, you need to implement it for all binary operations. I think you can refactor the implementation so that you don't need to add if branches to all binary operators.

File: crates/parser2/src/parser/expr.rs [hunk 4]
```diff
@@ -325,6 +351,27 @@ fn is_lt_eq<S: TokenStream>(parser: &mut Parser<S>) -> bool {
...
+    parser.dry_run(|parser| {
+        parser.set_newline_as_trivia(false);
+        if parser.current_kind() == Some(SyntaxKind::Eq) {
+            parser.bump();
+            true
+        } else {
+            false
+        }
+    })
+}
```
Comment (Y-Nak) [inline crates/parser2/src/parser/expr.rs:374]:
```suggestion

fn is_aug<S: TokenStream>(parser: &mut Parser<S>) -> bool {
    parser.dry_run(|parser| {
        if !bump_aug_assign_op(parser) {
            return false;
        }

        parser.set_newline_as_trivia(false);
        parser.current_kind() == Some(SyntaxKind::Eq)
    })
}

fn is_asn<S: TokenStream>(parser: &mut Parser<S>) -> bool {
    parser.dry_run(|parser| {
        parser.set_newline_as_trivia(false);
        if parser.current_kind() == Some(SyntaxKind::Eq) {
            parser.bump();
            true
        } else {
            false
        }
    })
}
```
nit: please add newlines.

File: crates/parser2/src/ast/expr.rs (hunk 1 above)
Comment (Y-Nak) [reply crates/parser2/src/ast/expr.rs:976]: Oh, sorry. I missed this is an AST test, and all AST tests use `wasm_bindgen_test`. Please ignore this comment.

**Comment by saifalkatout** [comment]
> First and foremost, please learn the basic usage of git. And please use git in the proper way since the next PR. There is a vast amount of learning resources available online. This is the third PR on the same issue. I think it is generally not preferable to have reviews dispersed across multiple PRs, and it also increases my workload (albeit slightly). While I believe that the flow where reviewers and authors work together to resolve issues in the code is excellent, but frankly speaking, I don't want to teach basic git usage.

Basically what I was trying to do is open a new PR and then cherry pick the commits from the old one. A simple rebase back into the old PR and deleting this one would fix the issue of having the work dispersed over 2 PRs, at any rate, apologies for the inconvenience.

File: crates/hir/src/span/transition.rs [hunk 5]
```diff
@@ -364,7 +363,7 @@ macro_rules! define_lazy_span_node {
                         fn f(origin: crate::span::transition::ResolvedOrigin, _: crate::span::transition::LazyArg) -> crate::span::transition::ResolvedOrigin {
                             origin.map(|node| <$sk_node as AstNode>::cast(node)
                                 .and_then(|n| n.$getter_node())
-                                .map(|n| n.syntax().clone().into()))
+                                .map(|n|  n.syntax().clone().into()))
```
Comment (Y-Nak) [inline crates/hir/src/span/transition.rs:366]:
```suggestion
                                .map(|n| n.syntax().clone().into()))
```

File: crates/hir/src/span/stmt.rs [hunk 6]
```diff
@@ -47,35 +47,4 @@ impl ChainInitiator for StmtRoot {
...
-                1 => {
-                    let span = stmt.lazy_span(body);
-                    assert_eq!("x += 1", db.text_at(top_mod, &span));
-                }
-                _ => unreachable!(),
-            }
-        }
-    }
-}
+mod tests {}
```
Comment (Y-Nak) [inline crates/hir/src/span/stmt.rs:50]:
```suggestion
```

File: crates/parser2/src/ast/expr.rs [hunk 7]
```diff
@@ -334,6 +338,48 @@ impl ParenExpr {
...
+impl AssignExpr {
+    /// Returns the expression of the lhs and rhs of the assignment.
+    pub fn lhs_expr(&self) -> Option<super::Expr> {
+        support::children(self.syntax()).next()
+    }
+
+    pub fn rhs_expr(&self) -> Option<super::Expr> {
+        support::children(self.syntax()).nth(1)
+    }
+    pub fn eq(&self) -> Option<SyntaxToken> {
```
Comment (Y-Nak) [inline crates/parser2/src/ast/expr.rs:355]:
```suggestion
    }
    
    pub fn eq(&self) -> Option<SyntaxToken> {
```

File: crates/parser2/src/syntax_kind.rs [hunk 8]
```diff
@@ -286,14 +286,13 @@ pub enum SyntaxKind {
     MatchExpr,
     /// `(1 + 2)`
     ParenExpr,
-
+    /// x = 1
+    AssignExpr,
+    /// x += 1
+    AugAssignExpr,
```
Comment (Y-Nak) [inline crates/parser2/src/syntax_kind.rs:292]:
```suggestion
    AugAssignExpr,
    
```

**Review by Y-Nak — COMMENTED** [review]
I left minor nits. I will merge this PR when the comments are resolved.

**Comment by sbillig** [comment]
> Basically what I was trying to do is open a new PR and then cherry pick the commits from the old one.

Instead of opening a new PR, you could have, for example, created a new branch locally, cherry-picked the commits to it, reset your original branch to the new branch head, and force pushed. With git, you can always make your local branch look exactly how you want it, then you can force push to github so that your PR reflects your local branch.

It's usually easiest to work on a new branch (with a name like "augassign-expr") for each PR, then if changes happen on the main branch (fe-v2), you can pull those changes to your local fe-v2 branch, and rebase your PR branch onto the main branch, and `git push --force` to github. This way, your PR will always only contain your commits, not a bunch of unrelated commits by other people. Anyway, being good at git is pretty important in modern software development, so it's worth the time investment to learn. (If you're using a gui, I'd recommend using the command line until you can do everything there, then feel free to use a gui for convenience for regular daily workflow.)

**Comment by Y-Nak** [comment]
LGTM. Thanks!
